### ISSUE TITLE
installation failed on volumio 2.502

### ISSUE THREAD

**Issue by eslei322** [ChrisPanda/volumio-es9018k2m-plugin#1]
hi, there,

installation failed with message:
********************************************************
volumio@volumio:/boot/k2m$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
No modules found, running "npm install"
********************************************************

installation instructions pls.

thanks

**Comment by cortegedusage** [comment]
Hi not sure if it would help but you could try 
npm i
before you install it. I'm about to check it myself
found it here: 
https://github.com/Saiyato/volumio-snapcast-plugin/issues/49

**Comment by cortegedusage** [comment]
ok little update,
yes it will install when you use
npm i, 
but if you enable the plugin and try to configure it. 
volumio will crash until you delete the plugin directory...

so tried a couple of things, disabling i2s dac enable another dac.
Aparently the aoide dac is recognised as the volumio dac...

anyway everything results in crashing volumio.
could anyone confirm it working with a previous version (until what version then).

cheers
dennis

**Comment by eslei322** [comment]
@cortegedusage 

thanks

**Comment by cortegedusage** [comment]
But does it work for you?
Can you get the plugin to work?
